Controllers/BorrowersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;

namespace HoneyBooks.Controllers
{
    public class BorrowersController : Controller
    {
        public ActionResult Create()
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Pages");
            }

            return View();
        }


        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Pages");
            }

            try
            {
                // Let's create a new borrower and fill it with form's data
                BL.Borrower borrower = new BL.Borrower();

                borrower.FirstName = collection["FirstName"];
                borrower.LastName = collection["LastName"];
                borrower.PersonId = collection["PersonId"];
                borrower.Address = collection["Address"];
                borrower.Telno = collection["Telno"];
                borrower.CategoryId = Convert.ToInt32(collection["CategoryId"]);
                borrower.Username = collection["Username"];
                borrower.Password = Settings.SecureString(collection["Password"]);
                
                borrower.create();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // Action to delete a borrower
        public ActionResult Delete(string PersonId)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Pages");
            }

            try
            {
                // Let's delete everything the borrower has borrowed
                Borrow.delete(PersonId);

                // Let's delete the borrower
                Borrower.delete(PersonId);
            }
            catch
            {
                return View("Error500");
            }

            return RedirectToAction("List");
        }

        public ActionResult Details(string PersonId)
        {
            Borrower borrower;

            try
            {
                borrower = BL.Borrower.getByPersonId(PersonId);
            }
            catch
            {
                return View("Error500");
            }

            return View(borrower);
        }


        public ActionResult Edit(string PersonId)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Pages");
            }

            Borrower borrower;

            try
            {
                borrower = BL.Borrower.getByPersonId(PersonId);
                borrower.Password = "";
            }
            catch
            {
                return View("Error500");
            }

            return View(borrower);
        }


        [HttpPost]
        public ActionResult Edit(string PersonId, FormCollection collection)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Pages");
            }

            try
            {
                // Let's create a new borrower and fill it with form's data
                BL.Borrower borrower = BL.Borrower.getByPersonId(PersonId);

                borrower.FirstName = collection["FirstName"];
                borrower.LastName = collection["LastName"];
                borrower.Address = collection["Address"];
                borrower.Telno = collection["Telno"];
                borrower.CategoryId = Convert.ToInt32(collection["CategoryId"]);
                borrower.Username = collection["Username"];

                // If the password has been changed, let's update it
                if (collection["Password"] != "")
                {
                    borrower.Password = Settings.SecureString(collection["Password"]);
                }

                // Let's edit the borrower
                borrower.edit();

                borrower.Password = "";

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Index(string PersonId = "")
        {
            if (Session["Borrower"] == null && Session["User"] == null)
            {
                return RedirectToAction("Login");
            }

            Borrower borrower = null;

            // If the borrower is in session, let's retrieve it
            if (Session["Borrower"] != null)
            {
                borrower = (Borrower)Session["Borrower"];
            }
            // If not, let's try to fetch it from database
            else
            {
                try
                {
                    borrower = Borrower.getByPersonId(PersonId);
                }
                catch
                {
                    return View("Error500");
                }
            }

            ViewBag.borrower = borrower;

            // Let's try to get all borrowed books by the borrower
            try
            {
                ViewBag.borrows = Borrow.getByPersonId(borrower.PersonId);
            }
            catch
            {
                return View("Error500");
            }

            return View();
        }

        public ActionResult List()
        {
            List<Borrower> borrowers;

            try
            {
                borrowers = BL.Borrower.getAll();
            }
            catch
            {
                return View("Error500");
            }

            return View();
        }


        public ActionResult Login()
        {
            if (Session["Borrower"] != null)
            {
                return RedirectToAction("Index");
            }

            if (Request.HttpMethod == "POST")
            {
                string login = Request.Form["username"];
                string password = Settings.SecureString(Request.Form["password"]);

                Borrower borrower = null;

                // Let's try to obtain the requested borrower by its login and password
                try
                {
                    borrower = Borrower.getByLoginAndPasswd(login, password);
                }
                catch
                {
                    return View("Error500");
                }

                if (borrower == null)
                {
                    ViewBag.error = "Please verify your login information.";
                }
                else
                {
                    Session["Borrower"] = borrower;
                    return RedirectToAction("Index");
                }
            }

            return View();
        }

        public ActionResult Logout()
        {
            // Let's remove the borrower from the session to log him/her out
            Session.Remove("Borrower");

            return RedirectToAction("Index", "Books");
        }


        public ActionResult RenewLoan(string barcode, string personId = "")
        {
            if (Session["Borrower"] == null && Session["User"] == null)
            {
                return RedirectToAction("Login");
            }

            Borrower borrower = null;

            // Let's retrieve the borrower from the session
            if (Session["Borrower"] != null)
            {
                borrower = (Borrower)Session["Borrower"];
            }
            // Otherwise, let's retrieve him/her from the database
            else
            {
                try
                {
                    borrower = Borrower.getByPersonId(personId);
                }
                catch
                {
                    return View("Error500");
                }
            }

            Category category;

            // Let's try to get the borrower's category to get the period of a loan
            try
            {
                category = Category.getById(borrower.CategoryId);
            }
            catch
            {
                return View("Error500");
            }

            // Let's try to renew the loan
            try
            {
                Borrow.renewLoan(barcode, category.Period);
                Session["RenewLoanSuccess"] = true;
            }
            catch
            {
                return View("Error500");
            }

            if (Session["Borrower"] != null)
                return RedirectToAction("Index");
            else
                return RedirectToAction("Index", new { PersonId = borrower.PersonId });
        }
    }
}

Views/Borrowers/Create.cshtml
@model BL.Borrower

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Borrower</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PersonId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PersonId)
            @Html.ValidationMessageFor(model => model.PersonId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telno)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telno)
            @Html.ValidationMessageFor(model => model.Telno)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryId)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Username)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Username)
            @Html.ValidationMessageFor(model => model.Username)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Views/Borrowers/Details.cshtml
@model BL.Borrower

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Borrower</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
        @Html.ValidationMessageFor(model => model.FirstName)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
        @Html.ValidationMessageFor(model => model.LastName)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.PersonId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PersonId)
        @Html.ValidationMessageFor(model => model.PersonId)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
        @Html.ValidationMessageFor(model => model.Address)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Telno)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Telno)
        @Html.ValidationMessageFor(model => model.Telno)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.CategoryId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryId)
        @Html.ValidationMessageFor(model => model.CategoryId)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Username)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Username)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>
</fieldset>

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Views/Borrowers/Edit.cshtml
@model BL.Borrower

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Borrower</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telno)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telno)
            @Html.ValidationMessageFor(model => model.Telno)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryId)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Username)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Username)
            @Html.ValidationMessageFor(model => model.Username)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password) (let the field empty to keep the old password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <p>
            <input type="submit" value="Edit" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Views/Borrowers/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home page</h2>
<p>Welcome @ViewBag.borrower.FirstName !</p>

@if (ViewBag.borrows.Count == 0)
{
    <p>You don't have any current borrowed books yet.</p>
}
else
{
<table>
    <tr>
        <th>Title</th>
        <th>Borrow date</th>
        <th>To be returned</th>
        <th>Operations</th>
    </tr>
    @foreach (var borrow in ViewBag.borrows)
    {
        <tr>
            <td>@borrow.BookTitle</td>
            <td>@borrow.BorrowDate.ToString("MM/dd/yyyy HH:mm")</td>
            <td>@borrow.ToBeReturnedDate.ToString("MM/dd/yyyy HH:mm")</td>
            <td>@Html.ActionLink("Renew the loan", "RenewLoan", new { barcode = borrow.Barcode, PersonId = ViewBag.borrower.PersonId })</td>
        </tr>
    }
</table>
}

Views/Borrowers/List.cshtml
@model IEnumerable<BL.Borrower>

@{
    ViewBag.Title = "List";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.FirstName)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.LastName)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.PersonId)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.Address)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.Telno)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.CategoryId)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.Username)
        </td>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { PersonId = item.PersonId }) |
                @Html.ActionLink("Details", "Details", new { PersonId = item.PersonId }) |
                @Html.ActionLink("View currently borrowed books", "Index", new { PersonId = item.PersonId }) |
                @Html.ActionLink("Delete", "Delete", new { PersonId = item.PersonId })
            </td>
        </tr>
    }

</table>

Views/Borrowers/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@if (ViewBag.error != null)
{
    <p>@ViewBag.error</p>
}

@using (Html.BeginForm("Login", "Borrowers", FormMethod.Post))
{
    <text>Username : </text> @Html.TextBox("username");<br />
    <text>Password : </text> @Html.Password("password");<br />

    <input type="submit" value="Log in" />
}